#-------------------------------
# General Site Settings

title: Hi I'm Wes
description: graphic design // illustration // web development
email: weskerdesign@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **G’day and welcome to my site.** I am an enthusiastic and creative Graphic designer with over 5 years work experience in both print and digital design fields. Want to make something look awesome? We can do it together.


skills:
- {name: Communication, value: '8'}
- {name: Organisation, value: '7'}
- {name: Learning, value: '7'}
- {name: Planning, value: '5'}
- {name: Visual Identity, value: '7'}
- {name: Layout Design, value: '8'}
- {name: Typography, value: '6'}
- {name: Web Development, value: '3'}

#-------------------------------
# Work Section

projects:
- {name: Digital Media Expo, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: International Jewellery Fair, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Chermside Galleria, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Holiday & Travel Show, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}- {name: Digital Media Expo, folder: 'proj-1', file: 'work/proj-1.html'}- {name: International Jewellery Fair, folder: 'proj-2', file: 'work/proj-2.html'}- {name: Chermside Galleria, folder: 'proj-3', file: 'work/proj-3.html'}- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-marianne.jpg', name: 'MARIANNE ROBERTS', title: 'Marketing Manager of Expertise Events', quote: '<p><strong>With quality of output and turnaround time paramount priorities, </strong> Wes’s work is both creative and productive. Wes is a team player who enjoys designing and his passion shines through in his work</p>', logo: 'expertislogo.jpg'}- {avatar: 'face-richardsedin.jpg', name: 'Richard Sedin', title: 'Group Events Manager of Stitches & Craft Show', quote: '<p><strong>It was a pleasure working with Wes</strong> on the many different project for the Stitches & Craft Shows. His attention to detail and his creative process, help launch the new branding of this Iconic event.</p>', logo: 'stitcheslogo.jpg'}- {avatar: 'face-garyj.jpg', name: 'Gary Johnston', title: 'Creative Director of Expertise Events', quote: '<p><strong>Atem doluptat mi, cusci omnitate</strong> sitate licietus dus et hilluptatio tem qui doluptiam, qui rem evendam, omnimin prem namenest, que voluptur, eniminc ipidem vollit quatem ve</p>', logo: 'odmalogo.jpg'}- {avatar: 'face-nicole.jpg', name: 'Nicole McLennan', title: 'Marketing Coordinator of All Craft Events', quote: '<p><strong>Atem doluptat mi, cusci omnitate</strong> sitate licietus dus et hilluptatio tem qui doluptiam, qui rem evendam, omnimin prem namenest, que voluptur, eniminc ipidem vollit quatem ve</p>', logo: 'craftlogo.jpg'}
  
  
#-------------------------------
# Contact Section
  
social:
- {icon: 'envelope', link: 'http://twitter.com/devtipsshow'}


  
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
  
  
  
  
  
  