#-------------------------------
# General Site Settings

title: Hi I'm Wes
description: graphic design // illustration // web development
email: weskerdesign@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Graphic Designer, Freelancer based in Sydney'


#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **G’day and welcome to my creative hub.** I am an enthusiastic and creative Graphic Designer with over five years’ experience in both print and digital design fields. If you want to make something looking outstanding, let me know – we can do it together!


skills:
- {name: Communication, value: '8'}
- {name: Organisation, value: '7'}
- {name: Learning, value: '7'}
- {name: Planning, value: '5'}
- {name: Visual Identity, value: '7'}
- {name: Layout Design, value: '8'}
- {name: Typography, value: '6'}
- {name: Web Development, value: '3'}

#-------------------------------
# Work Section

projects:
- {name: Digital Media Expo, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: International Jewellery Fair, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Chermside Galleria, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Holiday & Travel Show, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Smartfix, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Motorcycle & Friend Expo, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Odma|2015, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: All Craft events, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-marianne.jpg', name: 'MARIANNE ROBERTS', title: 'Marketing Manager', quote: '<p><strong>With quality of output and turnaround time paramount priorities, </strong> Wes’s work is both creative and productive. Wes is a team player who enjoys designing and his passion shines through in his work</p>', logo: 'expertislogo.jpg'}- {avatar: 'face-richardsedin.jpg', name: 'Richard Sedin', title: 'Group Events Manager of Stitches & Craft Show', quote: '<p><strong>It was a pleasure working with Wes</strong> on the many different project for the Stitches & Craft Shows. His attention to detail and his creative process, help launch the new branding of this Iconic event.</p>', logo: 'stitcheslogo.jpg'}- {avatar: 'face-garyj.jpg', name: 'Gary Johnston', title: 'Creative Director', quote: '<p><strong>I have worked with Wes for over a year</strong> and found him to be very a diligent and creative graphic designer. His knowledge far exceeds his experience especially with problem solving and web design.</p>', logo: 'odmalogo.jpg'}
  
  
#-------------------------------
# Contact Section
  
social:
- {icon: 'envelope', link: 'http://twitter.com/devtipsshow'}


  
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
  
  
  
  
  
  